language: java
cache:
  directories:
  - $HOME/.m2
jdk:
- oraclejdk8
sudo: 
  required
script:
- docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
- mvn clean package docker:build
- docker push jacobstom/destinationinfoservice:opdracht3